spring.application.name=innovatech-bff
server.port=8080

# Configuración básica
spring.datasource.url=jdbc:postgresql://localhost:5432/innovatech
spring.datasource.username=postgres
spring.datasource.password=15.RERM#@Vs