# ==================== Proyecto ====================
spring.application.name=innovatech-bff
server.port=8080

# ==================== JWT ====================
jwt.secret=innovatech2026_fullstack3_RichardMoreano
jwt.expiration=86400000   # 24 horas

# ==================== RestTemplate y Timeouts ====================
spring.resttemplate.connect-timeout=5000
spring.resttemplate.read-timeout=10000

# Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker.instances.projectService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.projectService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.resourceService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.resourceService.waitDurationInOpenState=5s